import React from 'react'

export const playersList = [


    {player: 'Patrick van Aanholt'
},{player: 'Tammy Abraham'},
{player: 'Che Adams'
},{player: 'Tosin Adarabioyo'},
{player: 'Adrián'},
{player: 'Sergio Agüero'
},{player: 'Ola Aina'},
{player: 'Rayan Aït Nouri'},
{player: 'Semi Ajayi'},
{player: 'Nathan Aké'},
{player: 'Marc Albrighton'},
{player: 'Thiago Alcántara'},
{player: 'Toby Alderweireld'},
{player: 'Rúnar Alex Rúnarsson'},
{player: 'Trent Alexander-Arnold'},
{player: 'Ezgjan Alioski'},
{player: 'Alisson'},
{player: 'Allan'},
{player:'Dele Alli'},
{player: 'Miguel Almirón'},
{player: 'Marcos Alonso'},
{player: 'Steven Alzate'},
{player: 'Daniel Amartey'},
{player: 'Ethan Ampadu'},
{player: 'Joachim Andersen'},
{player: 'Elliot Anderson'},
{player: 'Felipe Anderson'},
{player: 'Michail Antonio'},
{player: 'Alphonse Areola'},
{player: 'Stuart Armstrong'
},{player: 'Kepa Arrizabalaga'},
{player: 'Pierre-Emerick Aubameyang'},
{player: 'Serge Aurier'},
{player: 'Charlie Austin'},
{player: 'Jordan Ayew'},
{player: 'Luke Ayling'},
{player: 'César Azpilicueta'},
{player: 'Eric Bailly'},
{player: 'Fabián Balbuena'},
{player: 'George Baldock'},
{player: 'Gareth Bale'},
{player: 'Patrick Bamford'},
{player: 'Phil Bardsley'},
{player: 'Ross Barkley'},
{player: 'Ross Barkley'},
{player: 'Ashley Barnes'},
{player: 'Harvey Barnes'},
{player: 'Kyle Bartley'},
{player: 'Chris Basham'},
{player: 'Michy Batshuayi'},
{player: 'Jan Bednarek'},
{player: 'Donny van de Beek'},
{player: 'Héctor Bellerín'},
{player: 'Saïd Benrahma'},
{player: 'Josh Benson'},
{player: 'Christian Benteke'},
{player: 'Gaetano Berardi'},
{player: 'Jóhann Berg Guðmundsson'},
{player: 'Sander Berge'},
{player: 'Steven Bergwijn'},
{player: 'Bernard'},
{player: 'Bernardo'},
{player: 'Ryan Bertrand'},
{player: 'Yves Bissouma'},
{player: 'Jayden Bogle'},
{player: 'Willy Boly'},
{player: 'Jarrod Bowen'},
{player: 'Robbie Brady'},
{player: 'Rhian Brewster'},
{player: 'Nathan Broadhead'},
{player: 'Josh Brownhill'},
{player: 'Joe Bryan'},
{player: 'Kean Bryan'},
{player: 'Oliver Burke'},
{player: 'Dan Burn'},
{player: 'Jack Butland'},
{player: 'David Button'},
{player: 'Oskar Buur'},
{player: 'Willy Caballero'},
{player: 'Gary Cahill'},
{player: 'Tom Cairney'},
{player: 'Dominic Calvert-Lewin'},
{player: 'João Cancelo'},
{player: 'Ian Carlo Poveda'},
{player: 'Andy Carroll'},
{player: 'Scott Carson'},
{player: 'Fabio Carvalho'},
{player: 'Matty Cash'},
{player: 'Kiko Casilla'},
{player: 'Timothy Castagne'},
{player: 'Jonny Castro'},
{player: 'Ivan Cavaleiro'},
{player: 'Edinson Cavani'},
{player: 'Dani Ceballos'},
{player: 'Calum Chambers'},
{player: 'Ben Chilwell'},
{player: 'Hamza Choudhury'},
{player: 'Andreas Christensen'},
{player: 'Carney Chukwuemeka'
},{player: 'Ciaran Clark'},
{player: 'Nathaniel Clyne'},
{player: 'Conor Coady'},
{player: 'Séamus Coleman'},
{player: 'Aaron Connolly'},
{player: 'Liam Cooper'},
{player: 'Theo Corbeanu'},
{player: 'Jack Cork'},
{player: 'Hélder Costa'},
{player: 'Vladimír Coufal'},
{player: 'Aaron Cresswell'},
{player: 'Patrick Cutrone'},
{player: 'Stuart Dallas'},
{player: 'Scott Dann'},
{player: 'Karl Darlow'},
{player: 'Ben Davies'},
{player: 'Tom Davies'},
{player: 'Keinan Davis'},
{player: 'Leif Davis'},
{player: 'Craig Dawson'},
{player: 'Kevin De Bruyne'},
{player: 'Liam Delap'},
{player: 'Fabian Delph'},
{player: 'Leander Dendoncker'},
{player: 'Mbaye Diagne'},
{player: 'Amad Diallo'},
{player: 'Ibrahima Diallo'},
{player: 'Grady Diangana'},
{player: 'Raphael Dias Belloli'},
{player: 'Rúben Dias'},
{player: 'Eric Dier'},
{player: 'Lucas Digne'},
{player: 'Virgil van Dijk'},
{player: 'Issa Diop'},
{player: 'Moussa Djenepo'},
{player: 'Matt Doherty'},
{player: 'Gabriel Dos Santos'},
{player: 'Abdoulaye Doucouré'},
{player: 'Martin Dúbravka'},
{player: 'Paul Dummett'},
{player: 'Lewis Dunk'},{
player: 'Jimmy Dunne'},
{player: 'Ederson'},
{player: 'Kyle Edwards'},
{player: 'John Egan'},
{player: 'Anthony Elanga'},
{player: 'Ahmed Elmohamady'},
{player: 'Mohamed Elneny'},
{player: 'Jonny Evans'},
{player: 'Eberechi Eze'},
{player: 'Łukasz Fabiański'},
{player: 'Fabinho'},
{player: 'Bruno Fernandes'},
{player: 'Federico Fernández'},
{player: 'Fernandinho'},
{player: 'Sam Field'},{
player: 'Roberto Firmino'},
{player: 'John Fleck'},
{player: 'Phil Foden'},
{player: 'Wesley Fofana'},
{player: 'Pablo Fornals'},
{player: 'Fraser Forster'},
{player: 'Timothy Fosu-Mensah'},
{player: 'Tyrese Francois'},
{player: 'Ryan Fraser'},
{player: 'Fred'},
{player: 'Ryan Fredericks'},
{player: 'Christian Fuchs'},
{player: 'Darnell Furlong'},
{player: 'Conor Gallagher'},
{player: 'Eric García'},
{player: 'Dwight Gayle'},
{player: 'Jean-Philippe Gbamin'},
{player: 'David de Gea'},
{player: 'Anwar El Ghazi'},
{player: 'Kieran Gibbs'},
{player: 'Morgan Gibbs-White'},
{player: 'Billy Gilmour'},
{player: 'Olivier Giroud'},
{player: 'Ben Godfrey'},
{player: 'André Gomes'},
{player: 'Joe Gomez'},
{player: 'Anthony Gordon'},
{player: 'Karlan Grant'},
{player: 'Demarai Gray'},
{player: 'Jack Grealish'},
{player:'Mason Greenwood'},
{player: 'Pascal Groß'},
{player: 'Kamil Grosicki'},
{player: 'Vicente Guaita'},
{player:  'İlkay Gündoğan'},
{player: 'Antwoine Hackford'},
{player: 'Sébastien Haller'},
{player: 'Rekeem Harper'},
{player: 'Jack Harrison'},
{player: 'Kortney Hause'},
{player: 'Kai Havertz'},
{player: 'Isaac Hayden'},
{player: 'Michael Hector'},
{player: 'Ahmed Hegazi'},
{player: 'Dean Henderson'},
{player: 'Jordan Henderson'},
{player: 'Jeff Hendrick'},
{player: 'Pablo Hernández'},
{player: 'Son Heung-min'},
{player: 'Ki-Jana Hoever'},
{player: 'Rob Holding'},
{player: 'Mason Holgate'},
{player: 'Conor Hourihane'},
{player: 'Callum Hudson-Odoi'},
{player: 'Niall Huggins'},
{player: 'Pierre Højbjerg'},
{player: 'Odion Ighalo'},
{player: 'Kelechi Iheanacho'},{
player: 'Danny Ings'},
{player: 'Branislav Ivanović'},
{player:'Alex Iwobi'},
{player: 'José Izquierdo'},
{player: 'Phil Jagielka'},
{player: 'Alireza Jahanbakhsh'},
{player: 'Daniel James'},
{player: 'Reece James'},
{player: 'Alexandre Jankewitz'},
{player: 'Daniel Jebbison'},
{player: 'Gabriel Jesus'},
{player: 'Raúl Jiménez'},
{player: 'Joelinton'},
{player: 'Ben Johnson'},
{player: 'Sam Johnstone'},
{player: 'Curtis Jones'},
{player: 'Jorginho'},
{player: 'Willian José'},
{player: 'Diogo Jota'},
{player: 'James Justin'},
{player: 'Ozan Kabak'},
{player: 'Aboubakar Kamara'},
{player: 'Harry Kane'},
{player: "N'Golo Kanté"},
{player: 'Moise Kean'},
{player: 'Michael Keane'},
{player: 'Neeskens Kebano'},
{player: 'Naby Keïta'},
{player: 'Caoimhín Kelleher'},
{player: 'Martin Kelly'},
{player: 'Jonjoe Kenny'},
{player: 'Reda Khadra'},
{player: 'Max Kilman'},
{player: 'Joshua King'},
{player: 'Mateusz Klich'},
{player: 'Robin Koch'},
{player: 'Sead Kolašinac'},
{player: 'Terence Kongolo'},
{player: 'Ezri Konsa'},
{player: 'Cheikhou Kouyaté'},
{player: 'Mateo Kovačić'},
{player: 'Emil Krafth'},
{player: 'Filip Krovinović'},
{player: 'Alexandre Lacazette'},
{player: 'Adam Lallana'},
{player: 'Érik Lamela'},
{player: 'Tariq Lamptey'},
{player: 'Manuel Lanzini'},
{player:'Aymeric Laporte'},
{player: 'Jamaal Lascelles'},
{player: 'Maxime Le Marchand'},
{player: 'Mario Lemina'},
{player: 'Bernd Leno'},
{player: 'Khanya Leshabela'},
{player: 'Jamal Lewis'},
{player: 'Victor Lindelöf'},
{player: 'Jesse Lingard'},
{player: 'Jake Livermore'},
{player: 'Diego Llorente'},
{player: 'Hugo Lloris'},
{player: 'Giovani Lo Celso'},
{player: 'Ruben Loftus-Cheek'},
{player: 'Ruben Loftus-Cheek'},
{player: 'Kevin Long'},
{player: 'Shane Long'},
{player: 'Matthew Longstaff'},
{player: 'Sean Longstaff'},
{player: 'Ademola Lookman'},
{player: 'Max Lowe'},
{player: 'Matthew Lowton'},
{player: 'David Luiz'},
{player: 'Douglas Luiz'},
{player: 'John Lundstram'},
{player: 'Alexis Mac Allister'},
{player: 'James Maddison'},
{player: 'Harry Maguire'},
{player: 'Riyad Mahrez'},
{player: 'Ainsley Maitland-Niles'},
{player: 'Ainsley Maitland-Niles'},
{player: 'Josh Maja'},
{player: 'Sadio Mané'},
{player: 'Javier Manquillo'},
{player: 'Fernando Marçal'},
{player: 'Solly March'},
{player: 'Pablo Marí'},
{player: 'Anthony Martial'},
{player: 'Martinelli'},
{player: 'Emiliano Martínez'},
{player: 'Arthur Masuaku'},
{player: 'Juan Mata'},
{player: 'Jean-Philippe Mateta'},
{player: 'Nemanja Matić'},
{player: 'Joël Matip'},
{player: 'Neal Maupay'},
{player: 'James McArthur'},
{player: 'Oliver McBurnie'},
{player: 'Alex McCarthy'},
{player: 'James McCarthy'},
{player: 'John McGinn'},
{player: 'David McGoldrick'},
{player: 'Dwight McNeil'},
{player: 'Scott McTominay'},
{player: 'Ben Mee'},
{player: 'Hannibal Mejbri'},
{player: 'Benjamin Mendy'},
{player: 'Edouard Mendy'},
{player: 'Nampalys Mendy'},
{player: 'Illan Meslier'},
{player: 'Luka Milivojević'},
{player: 'James Milner'},
{player: 'Yerry Mina'},
{player: 'Takumi Minamino'},
{player: 'Takumi Minamino'},
{player: 'Tyrone Mings'},
{player:  'Tyrick Mitchell'},
{player: 'Aleksandar Mitrović'},
{player: 'Jakub Moder'},
{player: 'Jayson Molumby'},
{player: 'Wesley Moraes'},
{player: 'Wes Morgan'},
{player: 'Mason Mount'},
{player: 'Lucas Moura'},
{player: 'Lys Mousset'},
{player:  'João Moutinho'},
{player: 'Joel Mumbongo'},
{player: 'Jacob Murphy'},
{player: 'Shkodran Mustafi'},
{player: 'Marvelous Nakamba'},
{player: 'Iliman Ndiaye'},
{player: 'Wilfred Ndidi'},
{player: 'Tanguy Ndombele'},
{player: 'Reiss Nelson'},
{player: 'Pedro Neto'},
{player: 'Rúben Neves'},
{player: 'Eddie Nketiah'},
{player:  'Niels Nkounkou'},
{player:  'Dan Nlundulu'},
{player: 'Mark Noble'},
{player: 'Will Norris'},
{player: 'Oliver Norwood'},
{player: "Jack O'Connell"},
{player: "Dara O'Shea"},
{player: 'Michael Obafemi'},
{player:'Denis Odoi'},
{player:'Angelo Ogbonna'},
{player: 'Robin Olsen'},
{player: 'Josh Onomah'},
{player: 'Divock Origi'},
{player: 'Ben Osborn'},
{player: 'Owen Otasowie'},
{player: 'Alex Oxlade-Chamberlain'},
{player: 'Emerson Palmieri'},
{player: 'Thomas Partey'},
{player: 'Rui Patrício'},
{player: 'Bailey Peacock-Farrell'},
{player: 'Lee Peltier'},
{player: 'Nicolas Pépé'},
{player: 'Matheus Pereira'},
{player: 'Ricardo Pereira'},
{player: 'Ayoze Pérez'},
{player: 'Kalvin Phillips'},
{player: 'Matt Phillips'},
{player: 'Nathaniel Phillips'},
{player: 'Jaden Philogene Bidace'},
{player: 'Jordan Pickford'},
{player: 'Erik Pieters'},
{player: 'Daniel Podence'},
{player: 'Paul Pogba'},
{player:  'Nick Pope'},
{player:  'Dennis Praet'},
{player: 'Davy Pröpper'},
{player: 'Christian Pulisic'},
{player: 'Aaron Ramsdale'},
{player: 'Jacob Ramsey'},
{player: 'Kayne Ramsey'},
{player: 'Darren Randolph'},
{player: 'Marcus Rashford'},
{player: 'Tim Ream'},
{player: 'Nathan Redmond' },
{player: 'Harrison Reed'},
{player: 'Sergio Reguilón'},
{player: 'Bobby Reid'},
{player: 'Declan Rice'},
{player: 'Lewis Richardson'},
{player: 'Richarlison'},
{player: 'Jaïro Riedewald'},
{player: 'Matt Ritchie'},
{player: 'Tyler Roberts' },
{player: 'Andrew Robertson'},
{player: 'Antonee Robinson'},
{player: 'Callum Robinson'},
{player: 'Jack Robinson'},
{player: 'Hal Robson-Kanu'},
{player: 'Marek Rodák'},
{player: 'Joe Rodon'},
{player: 'Rodri'},
{player: 'Rodrigo'},
{player: 'James Rodríguez'},
{player: 'Jay Rodriguez'},
{player: 'Oriol Romeu'},
{player:    'John Ruddy'},
{player: 'Antonio Rüdiger'},
{player: 'Mathew Ryan'},
{player: 'Mathew Ryan'},
{player: 'Allan Saint-Maximin'},
{player: 'Romain Saïss'},
{player: 'Bukayo Saka'},
{player: 'Mamadou Sakho'},
{player: 'Mohamed Salah'},
{player: 'Mohammed Salisu'},
{player: 'Davinson Sánchez'},
{player: 'Robert Sánchez'},
{player: 'Morgan Sanson'},
{player: 'Romaine Sawyers'},
{player: 'Dane Scarlett'},
{player: 'Fabian Schär'},
{player: 'Jeffrey Schlupp'},
{player: 'Kasper Schmeichel'},
{player: 'Nélson Semedo'},
{player: 'Femi Seriki'},
{player: 'Jamie Shackleton'},
{player: 'Xherdan Shaqiri'},
{player: 'Billy Sharp'},
{player: 'Luke Shaw'},
{player: 'Jonjo Shelvey'},
{player: 'Shola Shoretire'},
{player: 'Gylfi Sigurðsson'},
{player: 'Bernardo Silva'},
{player: 'Fábio Silva'},
{player: 'Thiago Silva'}, 
{player: 'Moussa Sissoko'},
{player: 'Islam Slimani'},
{player: 'William Smallbone'},
{player:  'Emile Smith-Rowe'},
{player: 'Robert Snodgrass'},
{player: 'Robert Snodgrass'},
{player: 'Cédric Soares'},
{player: 'Tomáš Souček'},
{player: 'Çağlar Söyüncü'},
{player: 'Zack Steffen'},
{player: 'Dale Stephens'},
{player: 'Jack Stephens'},
{player: 'Raheem Sterling'},
{player: 'Enda Stevens'},
{player: 'John Stones'},
{player: 'Pascal Struijk'},
{player: 'Japhet Tanganga'},
{player: 'Matt Targett'},
{player: 'James Tarkowski'},
{player: 'Percy Tau'},
{player: 'Sidnei Tavares'},
{player: 'Charlie Taylor'},
{player: 'Neil Taylor'},
{player: 'Allan Tchaptchet'},
{player: 'Nathan Tella'},
{player: 'Alex Telles'},
{player: 'Kenny Tete'},
{player: 'William Thomas Fish'},
{player: 'Luke Thomas'},
{player: 'Youri Tielemans'},
{player:  'Kieran Tierney'},
{player: 'James Tomkins'},
{player: 'Fikayo Tomori'},
{player: 'Ferrán Torres'},
{player: 'Cenk Tosun'},
{player: 'Andros Townsend'},
{player: 'Conor Townsend'},
{player:  'Adama Traoré'},
{player: 'Bertrand Traoré'},
{player: 'Trézéguet'},
{player: 'Leandro Trossard'},
{player: 'Kostas Tsimikas'},
{player: 'Axel Tuanzebe'},
{player: 'Cengiz Ünder'},
{player: 'Yan Valery'},
{player: 'Jamie Vardy'},
{player: 'Joël Veltman'},
{player: 'Jannik Vestergaard'},
{player: 'Rúben Vinagre'},
{player: 'Carlos Vinícius'},
{player: 'João Virgínia'},
{player: 'Vitinha'},
{player: 'Jake Vokins'},
{player: 'Matěj Vydra'},
{player: 'Theo Walcott'},
{player: 'Theo Walcott'},
{player: 'Kyle Walker'},
{player: 'Kyle Walker-Peters'},
{player: 'Aaron Wan-Bissaka'},
{player: 'Joel Ward'},
{player: 'James Ward-Prowse'},
{player: 'Ollie Watkins'},
{player: 'Caleb Watts'},
{player: 'Adam Webster'},
{player: 'Danny Welbeck'},
{player: 'Timo Werner'},
{player: 'Ashley Westwood'},
{player:  'Ben White'},
{player: 'Georginio Wijnaldum'},
{player: 'Brandon Williams'},
{player: 'Neco Williams'},
{player: 'Rhys Williams'},
{player: 'Willian'},
{player: 'Joe Willock'},
{player: 'Joe Willock'},
{player: 'Callum Wilson'},
{player: 'Harry Winks'},
{player: 'Chris Wood'},
{player: 'Granit Xhaka'},
{player: 'Andriy Yarmolenko'},
{player: 'DeAndre Yedlin'},
{player: 'Okay Yokuşlu'},
{player: 'Wilfried Zaha'},
{player:  'Andre-Frank Zambo Anguissa'},
{player: 'Andi Zeqiri'},
{player: 'Oleksandr Zinchenko'},
{player:    'Hakim Ziyech'},
{player: 'Kurt Zouma'},
{player: 'Martin Ødegaard'},
]

// /*







// */